name: flutter_graphql_tutorial
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ">=1.0.0 <2.0.0"
  gql_build: ^0.1.4+2
  gql_code_builder: ^0.1.4+1
flutter:
  uses-material-design: true
